/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Frames;

import com.Contorllers.PlayBO;
import com.Models.PlayVO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class crudPlay extends javax.swing.JFrame {

    int xMouse, yMouse;
    String formato;

    private DefaultTableModel modelo;

    public crudPlay() {
        initComponents();
        llenarTabla();

    }

    public void llenarTabla() {

        

        modelo = new DefaultTableModel();
        modelo.addColumn("TITULO");
        modelo.addColumn("FECHA");
        modelo.addColumn("CONSOLA");
        modelo.addColumn("GENERO");
        modelo.addColumn("FORMATO");
        modelo.addColumn("DIRECTOR");
        TDatos.setModel(modelo);

        List<PlayVO> juegosPlay = new PlayBO().consultar_todos();
        for (PlayVO play : juegosPlay) {
            String fila[] = {play.getTitulo(), play.getFecha(), play.getConsola(), play.getGenero(), play.getFormato(), play.getDirector()};
            modelo.addRow(fila);
        }
        
        TDatos.getColumnModel().getColumn(0).setPreferredWidth(200);
        TDatos.getColumnModel().getColumn(1).setPreferredWidth(70);
        TDatos.getColumnModel().getColumn(2).setPreferredWidth(80);
        TDatos.getColumnModel().getColumn(3).setPreferredWidth(55);
        TDatos.getColumnModel().getColumn(4).setPreferredWidth(80);
        
        
    }

    public void limpiar() {
        tfTitulo.setText(null);
        txtDate.setText(null);
        cbConsola.setSelectedIndex(0);
        cbGenero.setSelectedIndex(0);
        SelccionFormato.clearSelection();
        tfDirector.setText(null);
    }

    private String SeleccionarFormato() {

        if (rbColeccionista.isSelected()) {
            formato = rbColeccionista.getText();
        }
        if (rbDigital.isSelected()) {
            formato = rbDigital.getText();
        }
        if (rbFisico.isSelected()) {
            formato = rbFisico.getText();
        }
        return formato;
    }

    private boolean RetornarFormato() {
        PlayVO play = new PlayBO().consultar_por_titulo(tfTitulo.getText());
        boolean eleccion = false;
        if (play.getFormato().equals("Fisico")) {
            rbFisico.setSelected(true);
            eleccion = true;
        } else if (play.getFormato().equals("Digital")) {
            rbDigital.setSelected(true);
            eleccion = true;
        } else if (play.getFormato().equals("Coleccionista")) {
            rbColeccionista.setSelected(true);
            eleccion = true;
        }
        return eleccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelccionFormato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jpExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jpIngresarDatos = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        txtPublic = new javax.swing.JLabel();
        txtConsola = new javax.swing.JLabel();
        txtGenero = new javax.swing.JLabel();
        txtFormato = new javax.swing.JLabel();
        txtDirector = new javax.swing.JLabel();
        cbConsola = new javax.swing.JComboBox<>();
        rbDigital = new javax.swing.JRadioButton();
        rbFisico = new javax.swing.JRadioButton();
        rbColeccionista = new javax.swing.JRadioButton();
        tfDirector = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        jpBotones = new javax.swing.JPanel();
        btnCargarDatos = new javax.swing.JPanel();
        txtCargarDatos = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        txtActualizar = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JPanel();
        txtInsertar = new javax.swing.JLabel();
        jpID1 = new javax.swing.JPanel();
        btnConsultar1 = new javax.swing.JPanel();
        txtConsultar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        tfConverFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setOpaque(false);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jpExit.setBackground(new java.awt.Color(9, 9, 11));
        jpExit.setForeground(new java.awt.Color(9, 9, 11));
        jpExit.setOpaque(false);
        jpExit.setPreferredSize(new java.awt.Dimension(40, 40));

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpExitLayout = new javax.swing.GroupLayout(jpExit);
        jpExit.setLayout(jpExitLayout);
        jpExitLayout.setHorizontalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpExitLayout.setVerticalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 960, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jpIngresarDatos.setOpaque(false);

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitulo.setText("Titulo");

        tfTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPublic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPublic.setText("Fecha Publicación");

        txtConsola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConsola.setText("Consola");

        txtGenero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGenero.setText("Genero");

        txtFormato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFormato.setText("Formato");

        txtDirector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDirector.setText("Director");

        cbConsola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbConsola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlayStation 1", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5" }));
        cbConsola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SelccionFormato.add(rbDigital);
        rbDigital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbDigital.setText("Digital");
        rbDigital.setOpaque(false);

        SelccionFormato.add(rbFisico);
        rbFisico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbFisico.setForeground(new java.awt.Color(255, 255, 255));
        rbFisico.setText("Fisico");
        rbFisico.setOpaque(false);

        SelccionFormato.add(rbColeccionista);
        rbColeccionista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbColeccionista.setForeground(new java.awt.Color(255, 255, 255));
        rbColeccionista.setText("Coleccionista");
        rbColeccionista.setOpaque(false);

        tfDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "RPG", "Aventuras", "Acción", "Carreras", "Musical" }));
        cbGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpIngresarDatosLayout = new javax.swing.GroupLayout(jpIngresarDatos);
        jpIngresarDatos.setLayout(jpIngresarDatosLayout);
        jpIngresarDatosLayout.setHorizontalGroup(
            jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGenero)
                            .addComponent(txtTitulo)
                            .addComponent(txtConsola)
                            .addComponent(txtPublic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbConsola, 0, 213, Short.MAX_VALUE)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbGenero, 0, 213, Short.MAX_VALUE)
                            .addComponent(txtDate))
                        .addGap(41, 41, 41))
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtDirector)
                        .addGap(152, 152, 152)
                        .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtFormato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbDigital)
                        .addGap(18, 18, 18)
                        .addComponent(rbFisico)
                        .addGap(18, 18, 18)
                        .addComponent(rbColeccionista)
                        .addGap(28, 28, 28))))
        );
        jpIngresarDatosLayout.setVerticalGroup(
            jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPublic)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConsola)
                    .addComponent(cbConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtGenero)
                        .addGap(24, 24, 24)
                        .addComponent(txtFormato))
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbDigital)
                            .addComponent(rbFisico)
                            .addComponent(rbColeccionista))))
                .addGap(18, 18, 18)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDirector)
                    .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jpIngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 490, 300));

        jpBotones.setOpaque(false);

        btnCargarDatos.setBackground(new java.awt.Color(48, 18, 7));
        btnCargarDatos.setForeground(new java.awt.Color(49, 78, 146));
        btnCargarDatos.setToolTipText("");
        btnCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargarDatosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCargarDatosMousePressed(evt);
            }
        });

        txtCargarDatos.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtCargarDatos.setForeground(new java.awt.Color(224, 124, 48));
        txtCargarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCargarDatos.setText("Cargar Datos");
        txtCargarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCargarDatosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCargarDatosLayout = new javax.swing.GroupLayout(btnCargarDatos);
        btnCargarDatos.setLayout(btnCargarDatosLayout);
        btnCargarDatosLayout.setHorizontalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        btnCargarDatosLayout.setVerticalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEliminar.setBackground(new java.awt.Color(48, 18, 7));
        btnEliminar.setForeground(new java.awt.Color(49, 78, 146));
        btnEliminar.setToolTipText("");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        txtEliminar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(224, 124, 48));
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        txtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEditar.setBackground(new java.awt.Color(48, 18, 7));
        btnEditar.setForeground(new java.awt.Color(49, 78, 146));
        btnEditar.setToolTipText("");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });

        txtActualizar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtActualizar.setForeground(new java.awt.Color(224, 124, 48));
        txtActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActualizar.setText("Actualizar");
        txtActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtActualizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditarLayout.createSequentialGroup()
                .addComponent(txtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEnviar.setBackground(new java.awt.Color(48, 18, 7));
        btnEnviar.setForeground(new java.awt.Color(49, 78, 146));
        btnEnviar.setToolTipText("");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnviarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEnviarMousePressed(evt);
            }
        });

        txtInsertar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtInsertar.setForeground(new java.awt.Color(224, 124, 48));
        txtInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInsertar.setText("Insertar");
        txtInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtInsertarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInsertarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEnviarLayout = new javax.swing.GroupLayout(btnEnviar);
        btnEnviar.setLayout(btnEnviarLayout);
        btnEnviarLayout.setHorizontalGroup(
            btnEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEnviarLayout.createSequentialGroup()
                .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEnviarLayout.setVerticalGroup(
            btnEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jPanel1.add(jpBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 590, 70));

        jpID1.setOpaque(false);

        btnConsultar1.setBackground(new java.awt.Color(48, 18, 7));
        btnConsultar1.setForeground(new java.awt.Color(49, 78, 146));
        btnConsultar1.setToolTipText("");
        btnConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultar1MousePressed(evt);
            }
        });

        txtConsultar1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtConsultar1.setForeground(new java.awt.Color(224, 124, 48));
        txtConsultar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConsultar1.setText("Consultar");
        txtConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConsultar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConsultar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtConsultar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnConsultar1Layout = new javax.swing.GroupLayout(btnConsultar1);
        btnConsultar1.setLayout(btnConsultar1Layout);
        btnConsultar1Layout.setHorizontalGroup(
            btnConsultar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultar1Layout.createSequentialGroup()
                .addComponent(txtConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnConsultar1Layout.setVerticalGroup(
            btnConsultar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtConsultar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpID1Layout = new javax.swing.GroupLayout(jpID1);
        jpID1.setLayout(jpID1Layout);
        jpID1Layout.setHorizontalGroup(
            jpID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpID1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jpID1Layout.setVerticalGroup(
            jpID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpID1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jpID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 250, 80));

        TDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TDatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 740, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/645-6457086_logo-de-los-videojuegos-hd-png-download.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/16226731252609.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tfConverFecha.setBorder(null);
        tfConverFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfConverFecha.setEnabled(false);
        tfConverFecha.setFocusable(false);
        tfConverFecha.setOpaque(false);
        tfConverFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfConverFechaMousePressed(evt);
            }
        });
        jPanel1.add(tfConverFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        //jpExit.setBackground(Color.red);
        txtExit.setForeground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        jpExit.setBackground(new Color(9, 9, 11));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExitMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCargarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseEntered
        btnCargarDatos.setBackground(new Color(159, 165, 181));
        txtCargarDatos.setForeground(Color.white);
    }//GEN-LAST:event_txtCargarDatosMouseEntered

    private void txtCargarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseExited
        btnCargarDatos.setBackground(new Color(48, 18, 7));
        txtCargarDatos.setForeground(new Color(224, 124, 48));
    }//GEN-LAST:event_txtCargarDatosMouseExited
    /*
    private void txtCargarDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMousePressed
        limpiar();
    }                  txtCargarDatos//GEN-LAST:event_txtCargarDatosMousePressed
*/
    private void txtCargarDatosMousePressed(java.awt.event.MouseEvent evt) {

        try {
            PlayVO play = new PlayBO().consultar_por_titulo(tfTitulo.getText());

            tfTitulo.setText(play.getTitulo());
            txtDate.setText(play.getFecha());
            cbConsola.setSelectedItem(play.getConsola());
            cbGenero.setSelectedItem(play.getGenero());
            RetornarFormato();
            tfDirector.setText(play.getDirector());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Juego no encontrado");
        }
    }
    private void btnCargarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarDatosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarDatosMouseExited

    private void btnCargarDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarDatosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarDatosMousePressed

    private void txtEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseEntered
        btnEliminar.setBackground(new Color(159, 165, 181));
        txtEliminar.setForeground(Color.white);
    }//GEN-LAST:event_txtEliminarMouseEntered

    private void txtEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseExited
        btnEliminar.setBackground(new Color(48, 18, 7));
        txtEliminar.setForeground(new Color(224, 124, 48));
    }//GEN-LAST:event_txtEliminarMouseExited

    private void txtEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMousePressed
        try {
            PlayVO play = new PlayVO();
            play.setTitulo(tfTitulo.getText());
            boolean resultado = new PlayBO().eliminar_juego(play);
            String mensaje = resultado ? "el juego fue eliminado satisfactoriamente" : "el juego no pudo ser eliminado";

            //la sentencia this se usa para pasar un valor
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e);
        }
    }//GEN-LAST:event_txtEliminarMousePressed

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMousePressed

    private void txtActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMouseEntered
        btnEditar.setBackground(new Color(159, 165, 181));
        txtActualizar.setForeground(Color.white);
    }//GEN-LAST:event_txtActualizarMouseEntered

    private void txtActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMouseExited
        btnEditar.setBackground(new Color(48, 18, 7));
        txtActualizar.setForeground(new Color(224, 124, 48));
    }//GEN-LAST:event_txtActualizarMouseExited

    private void txtActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMousePressed
        try {
            PlayVO nuevo = new PlayVO();
            nuevo.setTitulo(tfTitulo.getText());
            nuevo.setFecha(txtDate.getText());
            nuevo.setConsola(cbConsola.getSelectedItem().toString());
            nuevo.setGenero(cbGenero.getSelectedItem().toString());
            nuevo.setFormato(SeleccionarFormato());
            nuevo.setDirector(tfDirector.getText());
            

            //carga los datos a través de 'nuevo'
            boolean resultado = new PlayBO().actualizar_juego(nuevo);
            String mensaje = resultado ? "El juego fue actualizado correctamente" : "El juego no pudo ser actualizado";
            //la sentencia 'this' se usa para pasar un valor a la misma clase
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e);
        }
    }//GEN-LAST:event_txtActualizarMousePressed

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMousePressed

    private void txtInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMouseEntered
        btnEnviar.setBackground(new Color(159, 165, 181));
        txtInsertar.setForeground(Color.white);
    }//GEN-LAST:event_txtInsertarMouseEntered

    private void txtInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMouseExited
        btnEnviar.setBackground(new Color(48, 18, 7));
        txtInsertar.setForeground(new Color(224, 124, 48));
    }//GEN-LAST:event_txtInsertarMouseExited

    private void txtInsertarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMousePressed
        try {
            PlayVO nuevo = new PlayVO();

            nuevo.setTitulo(tfTitulo.getText());
            nuevo.setConsola(cbConsola.getSelectedItem().toString());
            nuevo.setGenero(cbGenero.getSelectedItem().toString());
            nuevo.setFormato(SeleccionarFormato());
            nuevo.setDirector(tfDirector.getText());
            nuevo.setFecha(txtDate.getText());

            //carga los datos a través de 'nuevo'
            boolean resultado = new PlayBO().insertar_juego(nuevo);
            String mensaje = resultado ? "El juego fue registrado correctamente" : "El juego no fue registrado";
            //la sentencia 'this' se usa para pasar un valor a la misma clase
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error " + e);
        }
    }//GEN-LAST:event_txtInsertarMousePressed

    private void btnEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseExited

    }//GEN-LAST:event_btnEnviarMouseExited

    private void btnEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMousePressed

    }//GEN-LAST:event_btnEnviarMousePressed

    private void tfConverFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfConverFechaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfConverFechaMousePressed

    private void txtConsultar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultar1MouseEntered
        btnConsultar1.setBackground(new Color(159, 165, 181));
        txtConsultar1.setForeground(Color.white);
    }//GEN-LAST:event_txtConsultar1MouseEntered

    private void txtConsultar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultar1MouseExited
        btnConsultar1.setBackground(new Color(48, 18, 7));
        txtConsultar1.setForeground(new Color(224, 124, 48));
    }//GEN-LAST:event_txtConsultar1MouseExited

    private void txtConsultar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultar1MousePressed
        modelo.setRowCount(0);//Resetear Filas
        List<PlayVO> juegosXbox = null;
        if (tfTitulo.getText().equals("")) {
            llenarTabla();
        } else {
            juegosXbox = new ArrayList();
            juegosXbox.add(new PlayBO().consultar_por_titulo(tfTitulo.getText()));

            for (PlayVO play : juegosXbox){
            String fila[] = {play.getTitulo(), play.getFecha(), play.getConsola(), play.getGenero(), play.getFormato(), play.getDirector()};
            modelo.addRow(fila);
            
        }
        }

    }//GEN-LAST:event_txtConsultar1MousePressed

    private void btnConsultar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1MouseExited

    private void btnConsultar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.ButtonGroup SelccionFormato;
    private javax.swing.JTable TDatos;
    private javax.swing.JPanel btnCargarDatos;
    private javax.swing.JPanel btnConsultar1;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnEnviar;
    private javax.swing.JComboBox<String> cbConsola;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpExit;
    private javax.swing.JPanel jpID1;
    private javax.swing.JPanel jpIngresarDatos;
    private javax.swing.JRadioButton rbColeccionista;
    private javax.swing.JRadioButton rbDigital;
    private javax.swing.JRadioButton rbFisico;
    private javax.swing.JTextField tfConverFecha;
    private javax.swing.JTextField tfDirector;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JLabel txtActualizar;
    private javax.swing.JLabel txtCargarDatos;
    private javax.swing.JLabel txtConsola;
    private javax.swing.JLabel txtConsultar1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtDirector;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtFormato;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtInsertar;
    private javax.swing.JLabel txtPublic;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
