/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Frames;

import com.Contorllers.SwitchBO;
import com.Models.SwitchVO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class crudSwitch extends javax.swing.JFrame {

    int xMouse, yMouse;
    String formato;
    
    private DefaultTableModel modelo;
    
    public crudSwitch() {
        initComponents();
        llenarTabla();
    }
    
    public void llenarTabla() {

        

        modelo = new DefaultTableModel();
        modelo.addColumn("TITULO");
        modelo.addColumn("FECHA");
        modelo.addColumn("CONSOLA");
        modelo.addColumn("GENERO");
        modelo.addColumn("FORMATO");
        modelo.addColumn("DIRECTOR");
        TDatos.setModel(modelo);

        List<SwitchVO> juegosSwitch = new SwitchBO().consultar_todos();
        for (SwitchVO Switch : juegosSwitch) {
            String fila[] = { Switch.getTitulo(), Switch.getFecha(), Switch.getConsola(), Switch.getGenero(), Switch.getFormato(), Switch.getDirector()};
            modelo.addRow(fila);
        }
        
        TDatos.getColumnModel().getColumn(0).setPreferredWidth(200);
        TDatos.getColumnModel().getColumn(1).setPreferredWidth(40);
        TDatos.getColumnModel().getColumn(2).setPreferredWidth(100);
        TDatos.getColumnModel().getColumn(3).setPreferredWidth(50);
        TDatos.getColumnModel().getColumn(4).setPreferredWidth(55);
        TDatos.getColumnModel().getColumn(5).setPreferredWidth(100);
        
        
    }
    
    public void limpiar() {
        tfTitulo.setText(null);
        txtDate.setText("");
        cbConsola.setSelectedIndex(0);
        cbGenero.setSelectedIndex(0);
        SeleccionFormato.clearSelection();
        tfDirector.setText(null);
    }
    
    private String SeleccionarFormato(){
        
        if(rbColeccionista.isSelected()){
            formato = rbColeccionista.getText();
        }
        if(rbDigital.isSelected()){
            formato = rbDigital.getText();
        }
        if(rbFisico.isSelected()){
            formato = rbFisico.getText();
        }
        return formato;
    }
    
    private boolean RetornarFormato() {
        SwitchVO Switch = new SwitchBO().consultar_por_titulo(tfTitulo.getText());
        boolean eleccion = false;
        if (Switch.getFormato().equals("Fisico")) {
            rbFisico.setSelected(true);
            eleccion = true;
        } else if (Switch.getFormato().equals("Digital")) {
            rbDigital.setSelected(true);
            eleccion = true;
        } else if (Switch.getFormato().equals("Coleccionista")) {
            rbColeccionista.setSelected(true);
            eleccion = true;
        }
        return eleccion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionFormato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jpExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        jPBotones = new javax.swing.JPanel();
        btnCargarDatos = new javax.swing.JPanel();
        txtCargarDatos = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        txtActualizar = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JPanel();
        txtInsertar = new javax.swing.JLabel();
        jpIngresarDatos = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        txtPublic = new javax.swing.JLabel();
        txtConsola = new javax.swing.JLabel();
        txtGenero = new javax.swing.JLabel();
        txtFormato = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        txtDirector = new javax.swing.JLabel();
        tfDirector = new javax.swing.JTextField();
        cbConsola = new javax.swing.JComboBox<>();
        rbDigital = new javax.swing.JRadioButton();
        rbFisico = new javax.swing.JRadioButton();
        rbColeccionista = new javax.swing.JRadioButton();
        txtDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDatos = new javax.swing.JTable();
        jpID1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JPanel();
        txtConsultar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setOpaque(false);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jpExit.setBackground(new java.awt.Color(9, 9, 11));
        jpExit.setForeground(new java.awt.Color(9, 9, 11));
        jpExit.setOpaque(false);
        jpExit.setPreferredSize(new java.awt.Dimension(40, 40));

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        txtExit.setForeground(new java.awt.Color(109, 149, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpExitLayout = new javax.swing.GroupLayout(jpExit);
        jpExit.setLayout(jpExitLayout);
        jpExitLayout.setHorizontalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpExitLayout.setVerticalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 960, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jPBotones.setOpaque(false);

        btnCargarDatos.setBackground(new java.awt.Color(180, 19, 25));
        btnCargarDatos.setForeground(new java.awt.Color(49, 78, 146));
        btnCargarDatos.setToolTipText("");
        btnCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargarDatosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCargarDatosMousePressed(evt);
            }
        });

        txtCargarDatos.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        txtCargarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCargarDatos.setText("Cargar Datos");
        txtCargarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCargarDatosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCargarDatosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCargarDatosLayout = new javax.swing.GroupLayout(btnCargarDatos);
        btnCargarDatos.setLayout(btnCargarDatosLayout);
        btnCargarDatosLayout.setHorizontalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        btnCargarDatosLayout.setVerticalGroup(
            btnCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEliminar.setBackground(new java.awt.Color(180, 19, 25));
        btnEliminar.setForeground(new java.awt.Color(49, 78, 146));
        btnEliminar.setToolTipText("");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        txtEliminar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        txtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnActualizar.setBackground(new java.awt.Color(180, 19, 25));
        btnActualizar.setForeground(new java.awt.Color(49, 78, 146));
        btnActualizar.setToolTipText("");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarMousePressed(evt);
            }
        });

        txtActualizar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        txtActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtActualizar.setText("Actualizar");
        txtActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtActualizarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarLayout.createSequentialGroup()
                .addComponent(txtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnEnviar.setBackground(new java.awt.Color(180, 19, 25));
        btnEnviar.setForeground(new java.awt.Color(49, 78, 146));
        btnEnviar.setToolTipText("");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnviarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEnviarMousePressed(evt);
            }
        });

        txtInsertar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtInsertar.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInsertar.setText("Insertar");
        txtInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtInsertarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInsertarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEnviarLayout = new javax.swing.GroupLayout(btnEnviar);
        btnEnviar.setLayout(btnEnviarLayout);
        btnEnviarLayout.setHorizontalGroup(
            btnEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEnviarLayout.createSequentialGroup()
                .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnEnviarLayout.setVerticalGroup(
            btnEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPBotonesLayout = new javax.swing.GroupLayout(jPBotones);
        jPBotones.setLayout(jPBotonesLayout);
        jPBotonesLayout.setHorizontalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPBotonesLayout.setVerticalGroup(
            jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jPanel1.add(jPBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 610, 70));

        jpIngresarDatos.setOpaque(false);

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitulo.setText("Titulo");

        tfTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPublic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPublic.setText("Fecha Publicación");

        txtConsola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtConsola.setText("Consola");

        txtGenero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGenero.setText("Genero");

        txtFormato.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFormato.setText("Formato");

        cbGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "RPG", "Aventuras", "Acción", "Carreras", "Musical" }));
        cbGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDirector.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDirector.setText("Director");

        tfDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbConsola.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbConsola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Game Boy", "Nintendo 64", "Nintendo GameCube", "Nintendo DS", "Nintendo Wii", "Nintendo Switch" }));
        cbConsola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SeleccionFormato.add(rbDigital);
        rbDigital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbDigital.setForeground(new java.awt.Color(255, 255, 255));
        rbDigital.setText("Digital");
        rbDigital.setOpaque(false);

        SeleccionFormato.add(rbFisico);
        rbFisico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbFisico.setText("Fisico");
        rbFisico.setOpaque(false);

        SeleccionFormato.add(rbColeccionista);
        rbColeccionista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbColeccionista.setForeground(new java.awt.Color(255, 255, 255));
        rbColeccionista.setText("Coleccionista");
        rbColeccionista.setOpaque(false);

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIngresarDatosLayout = new javax.swing.GroupLayout(jpIngresarDatos);
        jpIngresarDatos.setLayout(jpIngresarDatosLayout);
        jpIngresarDatosLayout.setHorizontalGroup(
            jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtDirector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addComponent(txtFormato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbDigital)
                        .addGap(18, 18, 18)
                        .addComponent(rbFisico)
                        .addGap(18, 18, 18)
                        .addComponent(rbColeccionista)
                        .addGap(28, 28, 28))
                    .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                        .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                                .addComponent(txtPublic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGenero)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtConsola))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTitulo)
                                    .addComponent(cbGenero, 0, 213, Short.MAX_VALUE)
                                    .addComponent(cbConsola, 0, 213, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))))
        );
        jpIngresarDatosLayout.setVerticalGroup(
            jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPublic)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsola)
                    .addComponent(cbConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbDigital)
                        .addComponent(rbFisico)
                        .addComponent(rbColeccionista))
                    .addComponent(txtFormato))
                .addGap(24, 24, 24)
                .addGroup(jpIngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDirector)
                    .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jpIngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 490, 300));

        TDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TDatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 740, 110));

        jpID1.setOpaque(false);

        btnConsultar.setBackground(new java.awt.Color(180, 19, 25));
        btnConsultar.setForeground(new java.awt.Color(49, 78, 146));
        btnConsultar.setToolTipText("");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultarMousePressed(evt);
            }
        });

        txtConsultar.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtConsultar.setForeground(new java.awt.Color(255, 255, 255));
        txtConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtConsultar.setText("Consultar");
        txtConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtConsultarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtConsultarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnConsultarLayout = new javax.swing.GroupLayout(btnConsultar);
        btnConsultar.setLayout(btnConsultarLayout);
        btnConsultarLayout.setHorizontalGroup(
            btnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConsultarLayout.createSequentialGroup()
                .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnConsultarLayout.setVerticalGroup(
            btnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpID1Layout = new javax.swing.GroupLayout(jpID1);
        jpID1.setLayout(jpID1Layout);
        jpID1Layout.setHorizontalGroup(
            jpID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpID1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jpID1Layout.setVerticalGroup(
            jpID1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpID1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jpID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 250, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/645-6457086_logo-de-los-videojuegos-hd-png-download.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/pelicula-de-super-mario-bros (1).jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        txtExit.setForeground(Color.red);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        txtExit.setForeground(new Color(109,149,255));
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExitMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCargarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseEntered
        btnCargarDatos.setBackground(new Color(58,162,49));
        txtCargarDatos.setForeground(Color.white);
    }//GEN-LAST:event_txtCargarDatosMouseEntered

    private void txtCargarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMouseExited
        btnCargarDatos.setBackground(new Color(180,19,25));
        txtCargarDatos.setForeground(Color.white);
    }//GEN-LAST:event_txtCargarDatosMouseExited

    private void txtCargarDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCargarDatosMousePressed
        try {
            SwitchVO Switch = new SwitchBO().consultar_por_titulo(tfTitulo.getText());

            tfTitulo.setText(Switch.getTitulo());
            txtDate.setText(Switch.getFecha());
            cbConsola.setSelectedItem(Switch.getConsola());
            cbGenero.setSelectedItem(Switch.getGenero());
            RetornarFormato();
            tfDirector.setText(Switch.getDirector());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Juego no encontrado");
        }    
    }//GEN-LAST:event_txtCargarDatosMousePressed

    private void btnCargarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarDatosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarDatosMouseExited

    private void btnCargarDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarDatosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarDatosMousePressed

    private void txtEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseEntered
        btnEliminar.setBackground(new Color(58,162,49));
        txtEliminar.setForeground(Color.white);
    }//GEN-LAST:event_txtEliminarMouseEntered

    private void txtEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseExited
        btnEliminar.setBackground(new Color(180,19,25));
        txtEliminar.setForeground(Color.white);
    }//GEN-LAST:event_txtEliminarMouseExited

    private void txtEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMousePressed
        try {
            SwitchVO Switch = new SwitchVO();
            Switch.setTitulo(tfTitulo.getText());
            boolean resultado = new SwitchBO().eliminar_juego(Switch);
            String mensaje = resultado ? "El juego fue eliminado satisfactoriamente" : "el juego no pudo ser eliminado";

            //la sentencia this se usa para pasar un valor
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error " + e);
        }
    }//GEN-LAST:event_txtEliminarMousePressed

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMousePressed

    private void txtConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultarMouseEntered
        btnConsultar.setBackground(new Color(58,162,49));
        txtConsultar.setForeground(Color.white);
    }//GEN-LAST:event_txtConsultarMouseEntered

    private void txtConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultarMouseExited
        btnConsultar.setBackground(new Color(180,19,25));
        txtConsultar.setForeground(Color.white);
    }//GEN-LAST:event_txtConsultarMouseExited

    private void txtConsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultarMousePressed
        modelo.setRowCount(0);//Resetear Filas
        List<SwitchVO> juegosSwitch = null;
        if (tfTitulo.getText().equals("")) {
            llenarTabla();
        } else {
            juegosSwitch = new ArrayList();
            juegosSwitch.add(new SwitchBO().consultar_por_titulo(tfTitulo.getText()));

            for (SwitchVO Switch : juegosSwitch){
            String fila[] = {Switch.getTitulo(), Switch.getFecha(), Switch.getConsola(), Switch.getGenero(), Switch.getFormato(), Switch.getDirector()};
            modelo.addRow(fila);
            
        }
        }
    }//GEN-LAST:event_txtConsultarMousePressed

    private void btnConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseExited

    private void btnConsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMousePressed

    private void txtActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMouseEntered
        btnActualizar.setBackground(new Color(58,162,49));
        txtActualizar.setForeground(Color.white);
    }//GEN-LAST:event_txtActualizarMouseEntered

    private void txtActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMouseExited
        btnActualizar.setBackground(new Color(180,19,25));
        txtActualizar.setForeground(Color.white);
    }//GEN-LAST:event_txtActualizarMouseExited

    private void txtActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtActualizarMousePressed
        
        try {
            SwitchVO nuevo = new SwitchVO();
            nuevo.setTitulo(tfTitulo.getText());
            nuevo.setConsola(cbConsola.getSelectedItem().toString());
            nuevo.setGenero(cbGenero.getSelectedItem().toString());
            nuevo.setFormato(SeleccionarFormato());
            nuevo.setDirector(tfDirector.getText());
            nuevo.setFecha(txtDate.getText());
            //carga los datos a través de 'nuevo'
            boolean resultado = new SwitchBO().actualizar_juego(nuevo);
            String mensaje = resultado?"El juego fue actualizado correctamente":"El juego no fue actualizado";
            //la sentencia 'this' se usa para pasar un valor a la misma clase
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error "+e);
        }
    }//GEN-LAST:event_txtActualizarMousePressed

    private void btnActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseExited

    private void btnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMousePressed

    private void txtInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMouseEntered
        btnEnviar.setBackground(new Color(58,162,49));
        txtInsertar.setForeground(Color.white);
    }//GEN-LAST:event_txtInsertarMouseEntered

    private void txtInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMouseExited
        btnEnviar.setBackground(new Color(180,19,25));
        txtInsertar.setForeground(Color.white);
    }//GEN-LAST:event_txtInsertarMouseExited

    private void txtInsertarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInsertarMousePressed
        try {
            SwitchVO nuevo = new SwitchVO();
            nuevo.setTitulo(tfTitulo.getText());
            nuevo.setConsola(cbConsola.getSelectedItem().toString());
            nuevo.setGenero(cbGenero.getSelectedItem().toString());
            nuevo.setFormato(SeleccionarFormato());
            nuevo.setDirector(tfDirector.getText());
            nuevo.setFecha(txtDate.getText());
            //carga los datos a través de 'nuevo'
            boolean resultado = new SwitchBO().insertar_juego(nuevo);
            String mensaje = resultado?"El juego fue registrado correctamente":"El juego no pudo ser registrado";
            //la sentencia 'this' se usa para pasar un valor a la misma clase
            JOptionPane.showMessageDialog(this, mensaje);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error "+e);
        }
    }//GEN-LAST:event_txtInsertarMousePressed

    private void btnEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseExited

    }//GEN-LAST:event_btnEnviarMouseExited

    private void btnEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMousePressed

    }//GEN-LAST:event_btnEnviarMousePressed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudSwitch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudSwitch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.ButtonGroup SeleccionFormato;
    private javax.swing.JTable TDatos;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnCargarDatos;
    private javax.swing.JPanel btnConsultar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnEnviar;
    private javax.swing.JComboBox<String> cbConsola;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpExit;
    private javax.swing.JPanel jpID1;
    private javax.swing.JPanel jpIngresarDatos;
    private javax.swing.JRadioButton rbColeccionista;
    private javax.swing.JRadioButton rbDigital;
    private javax.swing.JRadioButton rbFisico;
    private javax.swing.JTextField tfDirector;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JLabel txtActualizar;
    private javax.swing.JLabel txtCargarDatos;
    private javax.swing.JLabel txtConsola;
    private javax.swing.JLabel txtConsultar;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtDirector;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtFormato;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtInsertar;
    private javax.swing.JLabel txtPublic;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
