/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Frames;

import java.awt.Color;
/**
 *
 * @author andre
 */
public class SeleccionConsola extends javax.swing.JFrame {

    crudSwitch tercerFrame = new crudSwitch();
    crudXbox cuartoFrame = new crudXbox();
    //crudPlay quintoFrame = new crudPlay();
    
    int xMouse, yMouse;
    public SeleccionConsola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        txtNombreU = new javax.swing.JLabel();
        txtTexto = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jpExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        btnXbox = new javax.swing.JPanel();
        txtXbox = new javax.swing.JLabel();
        btnPlay = new javax.swing.JPanel();
        txtPlay = new javax.swing.JLabel();
        btnNintendo = new javax.swing.JPanel();
        txtNintendo = new javax.swing.JLabel();
        imgFondoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(51, 102, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreU.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        txtNombreU.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreU.setText("name");
        Fondo.add(txtNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 230, 60));

        txtTexto.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        txtTexto.setText("Selecciona la consola a trabajar");
        Fondo.add(txtTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 610, -1));

        Header.setOpaque(false);
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jpExit.setBackground(new java.awt.Color(190, 0, 2));
        jpExit.setForeground(new java.awt.Color(9, 9, 11));
        jpExit.setPreferredSize(new java.awt.Dimension(40, 40));

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpExitLayout = new javax.swing.GroupLayout(jpExit);
        jpExit.setLayout(jpExitLayout);
        jpExitLayout.setHorizontalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpExitLayout.setVerticalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jpExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Fondo.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        btnXbox.setBackground(new java.awt.Color(30, 82, 17));
        btnXbox.setForeground(new java.awt.Color(49, 78, 146));
        btnXbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXboxMouseExited(evt);
            }
        });

        txtXbox.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtXbox.setForeground(new java.awt.Color(17, 123, 17));
        txtXbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtXbox.setText("XBOX");
        txtXbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtXbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtXboxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtXboxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtXboxMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnXboxLayout = new javax.swing.GroupLayout(btnXbox);
        btnXbox.setLayout(btnXboxLayout);
        btnXboxLayout.setHorizontalGroup(
            btnXboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtXbox, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnXboxLayout.setVerticalGroup(
            btnXboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtXbox, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Fondo.add(btnXbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 160, 60));

        btnPlay.setBackground(new java.awt.Color(3, 121, 234));
        btnPlay.setForeground(new java.awt.Color(49, 78, 146));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });

        txtPlay.setBackground(new java.awt.Color(217, 219, 231));
        txtPlay.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtPlay.setForeground(new java.awt.Color(3, 65, 156));
        txtPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlay.setText("PLAYSTATION");
        txtPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPlayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlayMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPlayLayout = new javax.swing.GroupLayout(btnPlay);
        btnPlay.setLayout(btnPlayLayout);
        btnPlayLayout.setHorizontalGroup(
            btnPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnPlayLayout.setVerticalGroup(
            btnPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Fondo.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 160, 60));

        btnNintendo.setBackground(new java.awt.Color(73, 4, 5));
        btnNintendo.setForeground(new java.awt.Color(49, 78, 146));
        btnNintendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNintendoMouseExited(evt);
            }
        });

        txtNintendo.setBackground(new java.awt.Color(217, 219, 231));
        txtNintendo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        txtNintendo.setForeground(new java.awt.Color(190, 0, 2));
        txtNintendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNintendo.setText("NINTENDO");
        txtNintendo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNintendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNintendoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNintendoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNintendoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnNintendoLayout = new javax.swing.GroupLayout(btnNintendo);
        btnNintendo.setLayout(btnNintendoLayout);
        btnNintendoLayout.setHorizontalGroup(
            btnNintendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNintendo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnNintendoLayout.setVerticalGroup(
            btnNintendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNintendo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Fondo.add(btnNintendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 160, 60));

        imgFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/three-companies.jpg"))); // NOI18N
        imgFondoImagen.setPreferredSize(new java.awt.Dimension(600, 540));
        Fondo.add(imgFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        jpExit.setBackground(Color.red);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        jpExit.setBackground(new Color(189,1,2));
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExitMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void btnXboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXboxMouseExited

    }//GEN-LAST:event_btnXboxMouseExited

    private void txtXboxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXboxMousePressed
        this.setVisible(false);
        cuartoFrame.setVisible(true);
    }//GEN-LAST:event_txtXboxMousePressed

    private void txtXboxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXboxMouseExited
        btnXbox.setBackground(new Color(30,82,17));
        txtXbox.setForeground(new Color(17,123,17));
    }//GEN-LAST:event_txtXboxMouseExited

    private void txtXboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtXboxMouseEntered
        btnXbox.setBackground(new Color(232,1,18));
        txtXbox.setForeground(Color.white);
    }//GEN-LAST:event_txtXboxMouseEntered

    private void txtPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlayMouseEntered
        btnPlay.setBackground(new Color(17,123,17));
        txtPlay.setForeground(Color.white);
    }//GEN-LAST:event_txtPlayMouseEntered

    private void txtPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlayMouseExited
        btnPlay.setBackground(new Color(3,121,234));
        txtPlay.setForeground(new Color(3,65,156));
    }//GEN-LAST:event_txtPlayMouseExited

    private void txtPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlayMousePressed
        //this.setVisible(false);
        //quintoFrame.setVisible(true);
    }//GEN-LAST:event_txtPlayMousePressed

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayMouseExited

    private void txtNintendoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNintendoMouseEntered
        btnNintendo.setBackground(new Color(3,65,156));
        txtNintendo.setForeground(Color.white);
    }//GEN-LAST:event_txtNintendoMouseEntered

    private void txtNintendoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNintendoMouseExited
        btnNintendo.setBackground(new Color(73,4,5));
        txtNintendo.setForeground(new Color(190,0,2));
    }//GEN-LAST:event_txtNintendoMouseExited

    private void txtNintendoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNintendoMousePressed
        this.setVisible(false);
        tercerFrame.setVisible(true);
    }//GEN-LAST:event_txtNintendoMousePressed

    private void btnNintendoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNintendoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNintendoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnNintendo;
    private javax.swing.JPanel btnPlay;
    private javax.swing.JPanel btnXbox;
    private javax.swing.JLabel imgFondoImagen;
    private javax.swing.JPanel jpExit;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtNintendo;
    private javax.swing.JLabel txtNombreU;
    private javax.swing.JLabel txtPlay;
    private javax.swing.JLabel txtTexto;
    private javax.swing.JLabel txtXbox;
    // End of variables declaration//GEN-END:variables
}
